# Site settings
title: Sungyong David Baik
description: 'Sungyong David Baik Homepage'
url: 'http://baiksung.github.io'
baseurl: ''
profilepic: '/images/dsybaik.jpg'
bkimage: '/images/toronto_by_dsybaik.jpg'
google_analytics: UA-XXXXXX-X
# font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Sungyong David Baik'
  email: dsybaik@snu.ac.kr 
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  baiksung
#  linkedin_username:  thomas-z√ºhlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md']
